pipeline {

```
agent any

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Terraform Init') {
        steps {
            bat 'terraform init'
        }
    }

    stage('Terraform Plan') {
        steps {
            bat 'terraform plan'
        }
    }

}
```

}
