pipeline {
    agent any

    stages {

        stage('Terraform Init') {
            steps {
                dir('terraform-jenkins-demo') {
                    bat 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform-jenkins-demo') {
                    bat 'terraform plan'
                }
            }
        }
    }
}